# Generated by Django 3.1.4 on 2021-04-03 05:20

import apps.utils.imagenes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenConCalidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_original', models.ImageField(upload_to=apps.utils.imagenes.models.obtener_path_de_subida)),
                ('imagen_calidad_alta', models.ImageField(null=True, upload_to=apps.utils.imagenes.models.obtener_path_de_subida)),
                ('imagen_calidad_media', models.ImageField(null=True, upload_to=apps.utils.imagenes.models.obtener_path_de_subida)),
                ('imagen_calidad_baja', models.ImageField(null=True, upload_to=apps.utils.imagenes.models.obtener_path_de_subida)),
                ('estado_conversion', models.CharField(choices=[('SIN_CONVERTIR', 'Sin Convertir'), ('EN_PROCESO', 'En Proceso'), ('EN_ERROR', 'En Error'), ('CONVERTIDA', 'Convertida')], default='SIN_CONVERTIR', max_length=13)),
            ],
        ),
    ]
