# Generated by Django 3.1.4 on 2021-04-03 05:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '__first__'),
        ('utils', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.persona')),
            ],
            bases=('usuarios.persona',),
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10)),
                ('escuela', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=70)),
                ('abierta', models.BooleanField(default=True)),
                ('creada_en', models.DateField(default=django.utils.timezone.now)),
                ('imagen_con_calidades', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utils.imagenconcalidades')),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.persona')),
            ],
            bases=('usuarios.persona',),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado', models.CharField(choices=[('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('En espera', 'En espera')], default='En espera', max_length=9)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clases.alumno')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clases.clase')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clases.maestro'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='inscripciones',
            field=models.ManyToManyField(through='clases.Inscripcion', to='clases.Clase'),
        ),
    ]
